#!/bin/bash
process_options=""
process_force=0


function processLine {
	while read line
	do
		[ "${line}" == "" ] && continue
		echo "Checking \"${line}\""
		[ -e "${line}" -a ${process_force} -ne 1 ] && continue
		echo " . . . Processing \"${line}\""
		local_filename="$(basename "${line}")"
		[ ! -e $(dirname "${line}") ] && mkdir -p "$(dirname "${line}")"
		case ${local_filename} in
			keystore_password.txt)
				echo "changeit" >"${line}"
				;;
			database_password.txt)
				dd if=/dev/random bs=32 count=1 2>/dev/null | base64 | tr -c -d "[0-9a-zA-Z]" | cut -c 1-20 >"${line}"
				;;
			jmxremote.access)
				cat <<EOF >"${line}"
# Gives 'midpoint' user read-write access to JMX objects.
midpoint readwrite
EOF
				;;
			jmxremote.password)
				echo -n "midpoint " >"${line}"
				dd if=/dev/random bs=32 count=1 2>/dev/null | base64 | tr -c -d "[0-9a-zA-Z]" | cut -c 1-20 >>"${line}"
				;;
			*)
				echo "Unknown file : ${line}"
				;;
		esac
	done
}

function genKeyStore {
	while read line
	do
		echo "Checking keystore: ${line}"
		if [ ! -e ${line} -o ${process_force} -eq 1 ]
		then
	                [ ! -e $(dirname "${line}") ] && mkdir -p "$(dirname "${line}")"
			echo " . . . generating ${line} ( type : ${2:-jceks} ; keysize: ${1:-128} )"
			keytool -genseckey -alias default -keystore ${line} -storetype ${2:-jceks} -storepass changeit -keyalg AES -keysize ${1:-128} -keypass midpoint
		fi
	done
}

function checkStructure {
	while read line
	do
		echo "Checking volume existence: ${line}"
		if [ ! -e ${line} ]
		then
			echo " . . . New folder: ${line}"
			mkdir -p ${line}
		fi
	done
}

while [ "${1:0:1}" == "-" ]
do
	process_options="${process_options} ${1}"
	case ${1:1} in
		f)
			process_force=1
			;;
	esac
	shift
done

if [ "${1}" == "" ]
then
	echo "Trying to find docker-compose file in current location ($(pwd))"
	find -maxdepth 1 -type f -name "docker-compose*" -exec ${0} ${process_options} \{\} \;
	exit 0
else
	while [ "${1}" != "" ]
	do
		echo "Processing file: ${1}"
		[ $(grep ^secrets: "${1}" | wc -l) -gt 0 ] && sed -n "/^secrets:/,/^$/{/file:/{s/.*[[:space:]]\(.*\)$/\1/p}}" "${1}" | processLine
		sed -n "/volumes:/,/^$/{/keystore/{s/.*[[:space:]]\([^[:space:]]*\):\/opt\/midpoint\/var\/keystore.jceks$/\1/p}}" "${1}" | genKeyStore
		sed -n "/volumes:/,/^$/{s/.*[[:space:]]\([^:[:space:]]*\/[^:[:space:]]*\):.*$/\1/p}" "${1}" | checkStructure
		shift
	done
fi
echo "Done."

#       - ./cluster_files:/opt/midpoint-dirs-docker-entrypoint/:ro

