services:
    postgres:
        image: postgres:16-alpine
        environment:
            - POSTGRES_PASSWORD=db.secret.pw.007
            - POSTGRES_USER=midpoint
            - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
        volumes:
            - postgres_data:/var/lib/postgresql/data

    midpoint:
        image: evolveum/midpoint:4.8.3-alpine
        depends_on:
            postgres:
                condition: service_started
        command: >
            bash -c "
            cd /opt/midpoint ;
            bin/midpoint.sh init-native ;
            echo ' - - - - - - ' ;
            bin/ninja.sh -B info >/dev/null 2>/tmp/ninja.log ;
            grep -q \"ERROR\" /tmp/ninja.log && (
            bin/ninja.sh run-sql --create --mode REPOSITORY  ;
            bin/ninja.sh run-sql --create --mode AUDIT
            ) ||
            echo -e '\\n Repository init is not needed...' ;
            /opt/midpoint/bin/midpoint.sh container ;
            "
        ports:
            - 8080:8080
        environment:
            - MP_SET_midpoint_repository_jdbcUsername=midpoint
            - MP_SET_midpoint_repository_jdbcPassword=db.secret.pw.007
            - MP_SET_midpoint_repository_jdbcUrl=jdbc:postgresql://postgres:5432/midpoint
            - MP_SET_midpoint_repository_database=postgresql
            - MP_SET_midpoint_administrator_initialPassword=5ecR3t4ever
            - MP_UNSET_midpoint_repository_hibernateHbm2ddl=1
            - MP_NO_ENV_COMPAT=1
            - MP_INIT_CFG=/opt/midpoint/var
        volumes:
            - midpoint_home:/opt/midpoint/var

volumes:
    postgres_data:
    midpoint_home:
