#!/bin/bash

DIR=`dirname "$0"`
source $DIR/common.bash
if [[ -n "$1" ]]; then
  MP_VERSION=$1
else
  MP_VERSION=$tag
fi

fileName=${2:-"midpoint-dist-${MP_VERSION}.tar.gz"}
dry_run=${3:-0}
groupId="com.evolveum.midpoint"
artifactId="dist"
classifier="-dist"
type="tar.gz"
base="https://nexus.evolveum.com/nexus/repository"
groupIdUrl="${groupId//.//}"
filename="${artifactId}-${MP_VERSION}${classifier}.${type}"

MP_VER=""
URL=""
if [[ "${MP_VERSION}" != "latest" ]] ; then
  repo="releases"
  MP_VER=$(curl -k -s ${base}/${repo}/${groupIdUrl}/${artifactId}/maven-metadata.xml | grep "<version>" | sed "s/.*<version>\([^<]*\)<\/version>/\1/" | grep "^${MP_VERSION}$" | tail -1)
  [[ "${MP_VER}" == "" ]] && \
	  MP_VER=$(curl -k -s ${base}/${repo}/${groupIdUrl}/${artifactId}/maven-metadata.xml | grep "<version>" | sed "s/.*<version>\([^<]*\)<\/version>/\1/" | grep "^${MP_VERSION}" | grep -v "\-M" | tail -1)
  [[ "${MP_VER}" != "" ]] && URL="${base}/${repo}/${groupIdUrl}/${artifactId}/${MP_VER}/${artifactId}-${MP_VER}${classifier}.${type}"
fi
if [[ "${URL}" == "" ]] ; then
  repo="snapshots"
  if [[ "${MP_VERSION}" == "latest" ]] ; then
	  MP_VER=$(xmllint --xpath "string(//latest)" <(curl -k -s "${base}/${repo}/${groupIdUrl}/${artifactId}/maven-metadata.xml"))
  else
	  MP_VER=$(curl -k -s ${base}/${repo}/${groupIdUrl}/${artifactId}/maven-metadata.xml | grep "<version>" | sed "s/.*<version>\([^<]*\)<\/version>/\1/" | grep "^${MP_VERSION}$" | tail -1)
	  # fall back to provided value... If nothing found we can try directly provided version - in the worst case the URL will not be build up...
	  [[ "${MP_VER}" == "" ]] && MP_VER=${MP_VERSION}
  fi
  if [ "${MP_VER}" != "" ] ; then
	  timestamp=$(xmllint --xpath "string(//timestamp)" <(curl -k -s "${base}/${repo}/${groupIdUrl}/${artifactId}/${MP_VER}/maven-metadata.xml"))
	  buildnumber=$(xmllint --xpath "string(//buildNumber)" <(curl -k -s "${base}/${repo}/${groupIdUrl}/${artifactId}/${MP_VER}/maven-metadata.xml"))
	  URL="${base}/${repo}/${groupIdUrl}/${artifactId}/${MP_VER}/${artifactId}-${MP_VER%-SNAPSHOT}-${timestamp}-${buildnumber}${classifier}.${type}"
  fi
fi

if [[ "${URL}" == "" ]] ; then
  echo "Unknown tag"
  exit 1
fi

echo "Downloading midPoint $MP_VERSION (${fileName}) from $URL"
echo "--------------------------------------------------------------------"
[ ${dry_run} -eq 1 ] && exit 0
if [ -e $DIR/${fileName} ]
then
	curl -k -R --output $DIR/${fileName} --time-cond $DIR/${fileName} "$URL"
else
	curl -k -R --output $DIR/${fileName} "$URL"
fi
echo "-----------------------------------------"
echo "Checking the download..."
if tar -tf $DIR/${fileName} >/dev/null; then
  echo "OK"
  exit 0
else
  rm $DIR/${fileName}
  echo "The file was not downloaded correctly - downloaded data has been removed"
  exit 1
fi
