# MidPoint
 
MidPoint is the leading open source identity governance and administration platform (IGA).
It is a comprehensive feature-rich system that has been continuously developed and maintained by a full-time team of professionals.
MidPoint is available under the terms of Apache License and European Union Public License.
Its regular annual releases ensure midPoint is continuously moving forward while having stability and security as two of its highest priorities.

MidPoint is known for its excellent integration capabilities and data centralization, which enables organizations to be in control of identity and accesses it has.

## Docker Images

All midPoint docker images are published at link:https://hub.docker.com/r/evolveum/midpoint[Docker Hub].

### Download image:

.download image without building
[source,bash]
----
docker pull evolveum/midpoint
----

### Build from git repository  

.clone git repository
[source,bash]
----
git clone https://github.com/Evolveum/midpoint-docker.git
cd midpoint-docker
----

.build
[source,bash]
----
docker build -t evolveum/midpoint .
----

## See also

* link:https://docs.evolveum.com/midpoint/install/containers/[MidPoint In Container] docs page
* link:https://docs.evolveum.com/midpoint/quickstart/[Quick Start] docs page
