version: "3.3"

services:
  midpoint_server:
    image: evolveum/midpoint:4.0
    ports:
      - 8080:8080
    environment:
     - REPO_DATABASE_TYPE
     - REPO_JDBC_URL
     - REPO_HOST
     - REPO_PORT
     - REPO_DATABASE
     - REPO_USER
     - REPO_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - REPO_MISSING_SCHEMA_ACTION
     - REPO_UPGRADEABLE_SCHEMA_ACTION
     - REPO_SCHEMA_VERSION_IF_MISSING
     - REPO_SCHEMA_VARIANT
     - MP_KEYSTORE_PASSWORD_FILE /run/secrets/mp_keystore_password.txt
     - MP_MEM_MAX
     - MP_MEM_INIT
     - MP_JAVA_OPTS
     - TIMEZONE
    networks:
     - net
    secrets:
     - mp_database_password.txt
     - mp_keystore_password.txt
    volumes:
     - midpoint_home:/opt/midpoint/var

networks:
  net:
    driver: bridge

secrets:
  mp_database_password.txt:
    file: ./configs-and-secrets/midpoint/database_password.txt
  mp_keystore_password.txt:
    file: ./configs-and-secrets/midpoint/keystore_password.txt
    
volumes:
  midpoint_home:
