apiVersion: v1
kind: Secret
metadata:
  name: cert-mp-pg-demo
  namespace: mp-demo
stringData:
  Expiration: Dec 18 09:45:55 2066 GMT
  SAN: DNS:mp-pg-demo.mp-demo.local, DNS:www.mp-pg-demo.mp-demo.local, DNS:localhost, IP Address:127.0.0.1
data:
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV1d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktVd2dnU2hBZ0VBQW9JQkFRRGFnOENicVhyMmhOSmsKNlV5VFRpU1hwMm41ZUZTUnNhN3Fl
    YVBTWHRiaXNZa2c1WXJ0VWtWRFBKNk1FNW14OCtIbTM3bDRhb1FUSEZsdQo0REtNbjV3ODZIeWNZ
    VjY0T2ROWmkxSmNvcHJJUmlldk5ielI4L1NIbjNPRURYV0FiQ3ppRzRqMnNwYTM4QVllCmJ0cWRN
    RmlHK25UcmpBYUEvdjh4ZlJlT0U5TzRNaDdMZEZBb0J5NjVDSEd5d05TR0xLUm5CQ2V3ZHlpNWFo
    ZEIKem5EMnkzZFJXSjJaYWVlUFo0M1M3bGhjWW9YcWhYVFBRTGk1OXgvbjRabkMwUHhHTVNsSWor
    NzlKTzZNM0lUNgowYjhQNW94cnNKdHp0TUNiNnhlRWI2dzVubWNwQjJ3TDA2ak9zRGlMM2ZuTTUz
    UVR6MDRYWDNmUjhMRENXTXQ2CnNaVWFFR2NsQWdNQkFBRUNnZ0VBTDNTM3F0YkczcXovNkd5R2Rl
    TmRyUlh0dlFFMkZLSXJJNzhoSmZuMDN5ekIKWkVTVnhHNituaGlYTWtLN2VWdEc3MVlkT0pxaGJt
    a1V2ekN2cWJ5c09Nb2c3ZkZ6bWJ6dE9xQTRWZWYyaDVJOAo0aDlnajVSVXdmT09LZHFtYnlxUElO
    ZnNDZS9GTGROUjhPQVFXRno4ak92dDRvMzVoNkJabWN6YUJjQW1sZlRkCm1wZVNBejRDc3JDQVgr
    ZHpCOUZ3c3hnTDNRMmVsRGlwSUM5NW83b1VoYW9WUDEvUSt5VmdENDNPZkxPenR5cUEKWTFZMkF5
    NnFqV1ZPR1poTDdRai9RekpEbi90ZW53SCtRNG9xcnBvTHl4L215UGVtbXgzTUNkdHk2SFRtZVBH
    cQpyVmZ3TEFXa2tsc2s5L3FMRDdjT0tQWWprZ1QvWGFXMEp4R0JyVmhZNFFLQmdRRCtrbkN4M1dM
    M2hCVXFDSGRUCmY5V3VGcFdEd0M5cGQxT3NSVjAxdmRYVjIrTENlMThSL05ob1cxUjBYK1B4TStP
    bEUyYkE1K3RON0RUWGNiYXoKczJOUzV4ekQvT3BXT1V4VjhwYUREd2RrMUI4ZDFjRlB0TGZONTlT
    b3NnbEFyQ3lZMlRXUGJNVVVQY2hPMEdzTAo3cjlUMi8vRC8xczlrdFdxK0RhOFFGUTJpUUtCZ1FE
    YnZZalp1TTY4aTVHdlM1d3JxQm5EWXBwZHN6VTFzNFgyCmtDZFBmVkFQeXJSek9FaUZhRzI5OEYw
    dmt1azdpaE53ZXh1VGQ2dWlTRG8yZ3JPeXBxNHRFa3psYk5sQ2l1b0oKNnF3S2VSMlBiSjlTNXRl
    RUVCTjhINm5XdWk2RmVmNFJMYmJXME03TmQ0TXB3SUtjaERWTktySHh6UDl2eXVVcwpubDFvY0Rv
    RXZRS0JnUUMzNkREenZaek9kU1FZL282OXlyOGlpZnd2ZHZxSmRZUUVFd1E0VzlFTU0xTEk3dm1L
    CmRDQWVtOFFTWW1lNGk2VHNUMnpPOVh4L0NhSk85ajVuNmJOYVk4M2JKRzVpSmZpb3FwempSMHN2
    SXpMcmljMmkKZUVyRXZMTmJ2MnFCeHlCY3Q2WkMyL0F3SkVYOThnRXpXS0h0d2lRdWd0NTJTQXFG
    L2RVRkFIQVdDUUovRmxFcApsUE13Qy9ZZzFhellMNWJqQnZUOHVJZDYzL2xib2E4Q1R4QnJFUytG
    SkM2VEx2bHNLOTQ5bUpkVEdManRRSDlBClRiblp0S0doUitmK1dDYVZpZjVSMFBzOUZZVUdQL3VW
    ZlhyUGhjR0NiT2tFK21TbmxmT2hUQzJjaS9IWDIrYkkKcXdpSitGUXEvaEtQTVZZOEU1cENlRXha
    cFFEMlJaSFA2c3Q3R1FLQmdIRTYxZWJNUEhobUZHVzR5MnZyUVROcwpINUZxb2owOHpmcVJUL0hx
    ZDR0UzRVWUZNU05hcEczTHBzZFk4Z3cwd21pZzh5TU9QTENuNDVmWDJSVko2L0ZiCm5pcy9wQXB6
    aTk3Y1lWZ2ZxUHdjNGR2dTdRekcxWStyOEgzVUdMb2VubC9ncHhJYmZVS2dxa2gweE5melZKOVMK
    bS9MQUp2ZHZGSEdoSVFyWWxkc2QKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzekNDQXB1Z0F3SUJBZ0lCQVRBTkJna3Fo
    a2lHOXcwQkFRc0ZBREFaTVJjd0ZRWURWUVFERXc0dWJHOWoKWVd3Z1pHVnRieUJEUVRBZ0Z3MHlN
    akF5TURnd09UUTFOVFZhR0E4eU1EWTJNVEl4T0RBNU5EVTFOVm93SXpFaApNQjhHQTFVRUF4TVli
    WEF0Y0djdFpHVnRieTV0Y0Mxa1pXMXZMbXh2WTJGc01JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZB
    QU9DQVE4QU1JSUJDZ0tDQVFFQTJvUEFtNmw2OW9UU1pPbE1rMDRrbDZkcCtYaFVrYkd1Nm5tajBs
    N1cKNHJHSklPV0s3VkpGUXp5ZWpCT1pzZlBoNXQrNWVHcUVFeHhaYnVBeWpKK2NQT2g4bkdGZXVE
    blRXWXRTWEtLYQp5RVlucnpXODBmUDBoNTl6aEExMWdHd3M0aHVJOXJLV3QvQUdIbTdhblRCWWh2
    cDA2NHdHZ1A3L01YMFhqaFBUCnVESWV5M1JRS0FjdXVRaHhzc0RVaGl5a1p3UW5zSGNvdVdvWFFj
    NXc5c3QzVVZpZG1Xbm5qMmVOMHU1WVhHS0YKNm9WMHowQzR1ZmNmNStHWnd0RDhSakVwU0kvdS9T
    VHVqTnlFK3RHL0QrYU1hN0NiYzdUQW0rc1hoRytzT1o1bgpLUWRzQzlPb3pyQTRpOTM1ek9kMEU4
    OU9GMTkzMGZDd3dsakxlckdWR2hCbkpRSURBUUFCbzRINU1JSDJNQWtHCkExVWRFd1FDTUFBd0hR
    WURWUjBPQkJZRUZBYldXamtwTUMraW5SRkVoNG9naWQralJxU1JNRlFHQTFVZEl3Uk4KTUV1QUZD
    Y3FDaERDZm1oNStLcWNqY1loS0JGTlBXNE5vUjJrR3pBWk1SY3dGUVlEVlFRREV3NHViRzlqWVd3
    ZwpaR1Z0YnlCRFFZSVVWR0ZUVkh1aWlUc1ZYakswVWNRN1VYUjlvMkF3Q3dZRFZSMFBCQVFEQWdY
    Z01GSUdBMVVkCkVRUkxNRW1DR0cxd0xYQm5MV1JsYlc4dWJYQXRaR1Z0Ynk1c2IyTmhiSUljZDNk
    M0xtMXdMWEJuTFdSbGJXOHUKYlhBdFpHVnRieTVzYjJOaGJJSUpiRzlqWVd4b2IzTjBod1IvQUFB
    Qk1CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRgpCd01CTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFB
    a3VJQVpSMFlmZDFCQWdFTW5YK3VsczRBRHVGMmFGTG0yCnhnM2FNclVEWVhLUHQveThrTVZkQ29n
    aDdHUG9YajRJZEVhbnhBZm80RFFTUnVnOFVZaGorRTliMTlKaUNrRnoKem41K0dLaVJMNFM1dVlP
    UVFTbXdyTmVWWElqeElCVW1JUVM5OXdUNVN2ditOaUdFQkFiSDVXb3YrRVBYblJHWApENlNiM3Fh
    blBWK1B4Y3paQ2xzYzFIYURzOHlEMjVjRjVGcVpQa2FZRXQ1dGZvRHR2QlE5WWpXZlljQ2pUNDha
    Cm1lT3V6NjdWU3o5MlNpbGVTNCtscFoyTHQvc3FoWnhxTGdYenJyRjBkck5YaTVuSDRpbGpXVFlq
    R0ZSRDZNWjcKRnBORERxZUVnYWMxcGtYV28rb0hjTXZjQ3ZrSmpCa00xVUNCQXRpNG42MmhGOWpr
    b3RDSgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXakNDQWtLZ0F3SUJBZ0lVVkdGVFZIdWlp
    VHNWWGpLMFVjUTdVWFI5bzJBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVHQTFVRUF4TU9M
    bXh2WTJGc0lHUmxiVzhnUTBFd0hoY05Nakl3TWpBNE1EazBOVEU0V2hjTgpOREl3TWpBek1EazBO
    VEU0V2pBWk1SY3dGUVlEVlFRREV3NHViRzlqWVd3Z1pHVnRieUJEUVRDQ0FTSXdEUVlKCktvWklo
    dmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5BcnpFT09vVGdNbTR1N0F6d2xDbHJvMmVSV1Bx
    bWcKUnB1eHMzSi9CN0hDTW5Rbm5OVWRwZU9nMEFNYzYxSW1OZUVYZW9rMTVoOWNKNCtVc2FoMFdM
    dnExZ1I1NzFoUApLR3dYdDd3b2NORHIxRCtVNmVmQmZHZlJSY3ZQc0wvblJHTzZ2NmVkaDg0cWZ1
    THl6bmEweGY4RS9Vemx4MDhkCko3dzQxc1QzOG0xS0ZDNFFOeDRwb2VkZno4SHJndXRTbG1JUXZ4
    dGNHNm1neHN2UXA5U2xlNXZ4ekt2RTAxL0sKNUJ2dzMyRDBkRDhxQTVNRlJ5cDNqcEx6aldRc1RG
    bldRK2RLYU5PbS8wUk96Rmo1Wm1MVzc2RmI1MzA3ZmlIcgpCRndKTUIwN01aWWRpWDdaVnptZS82
    em5zNHBlOVUyOG5vbVhINWEwMUlvMlpYYnpTTlR2T1MwQ0F3RUFBYU9CCm1UQ0JsakFTQmdOVkhS
    TUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJRbktnb1F3bjVvZWZpcW5JM0cKSVNnUlRU
    MXVEVEJVQmdOVkhTTUVUVEJMZ0JRbktnb1F3bjVvZWZpcW5JM0dJU2dSVFQxdURhRWRwQnN3R1RF
    WApNQlVHQTFVRUF4TU9MbXh2WTJGc0lHUmxiVzhnUTBHQ0ZGUmhVMVI3b29rN0ZWNHl0RkhFTzFG
    MGZhTmdNQXNHCkExVWREd1FFQXdJQkJqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXSVB6cGs3
    Q01FWXdLeVFzOTUyY0VLU0sKY3VpbTF0bWw3eFZKZkROMUdEMkdVamhKTGg2UDJiQ1lUNGs2cmsv
    RW0zZjd5dXdqZVNNMldPYWRaWjlCNHkwMwo5Mmw5WUtCSVNZVzNuYjc5VkRwN1F6TkV2Q29LaGJ3
    SmNDT1k2bEQ4UmNWYWt0NFJ2MUVhTVVLdXozWkR6U0VJCkZsc0ZFTXRKMGtzNFVYTlNBUVdWdVo4
    VnJKU2RuQ2JlNVpRelkzelhibTNkNGNXOTN3L2FBVWNUK3F5UjJlU1AKZWI2R29YdHYvbTRqR2VY
    L2VkUnJUUTM0andNSEJOZ2U1RGM3a3dNMGNnUXdCcGhnbi9TNVdnd3Nsa3hLL3AzQgpxNmlOUERX
    bnNGMDhuRHpKNk1qY0dZT1RLbnc0L3locjJ5TzVFUitHNTA1Wk9PNFBEL2Q2M2dvaTI1UHZjQT09
    Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
type: kubernetes.io/tls
