ARG MP_DIR=/opt/midpoint
ARG maintainer=evolveum
ARG imagename=midpoint
ARG JAVA_VERSION=21

### values for Ubuntu based image ###
ARG base_image=ubuntu
ARG base_image_tag=22.04
####################################

### values for Rocky linux based image ###
#ARG base_image=rockylinux
#ARG base_image_tag=9.3
#####################################

### values for Alpine based image ###
#ARG base_image=alpine
#ARG base_image_tag=latest
#####################################

FROM ${base_image}:${base_image_tag} as java-17

ENV MP_SET_midpoint_repository_database=h2 \
 MP_SET_midpoint_repository_jdbcUrl=jdbc:h2:tcp://localhost:5437/midpoint \
 MP_SET_midpoint_repository_hibernateHbm2ddl=none \
 MP_SET_midpoint_repository_initializationFailTimeout=60000 \
 MP_SET_midpoint_repository_missingSchemaAction=create \
 MP_SET_midpoint_repository_upgradeableSchemaAction=stop

FROM ${base_image}:${base_image_tag} as java-21

ENV MP_SET_midpoint_repository_database=h2 \
 MP_SET_midpoint_repository_jdbcUrl=jdbc:h2:tcp://localhost:5437/./midpoint;DB_CLOSE_ON_EXIT=FALSE;LOCK_MODE=1;LOCK_TIMEOUT=100;MAX_LENGTH_INPLACE_LOB=10240;NON_KEYWORDS=VALUE \
 MP_SET_midpoint_repository_hibernateHbm2ddl=none \
 MP_SET_midpoint_repository_initializationFailTimeout=60000 \
 MP_SET_midpoint_repository_missingSchemaAction=create \
 MP_SET_midpoint_repository_upgradeableSchemaAction=stop

FROM java-${JAVA_VERSION}

ARG MP_DIR
ARG base_image
ARG base_image_tag
ARG maintainer
ARG imagename
ARG JAVA_VERSION

LABEL Vendor="${maintainer}"
LABEL ImageType="base"
LABEL ImageName="${imagename}"
LABEL ImageOS="${base_image}:${base_image_tag}"
LABEL Version="${MP_VERSION}"
LABEL org.opencontainers.image.authors="info@evolveum.com"

ENV MP_SET_file_encoding=UTF8 \
 MP_SET_midpoint_logging_alt_enabled=true \
 MP_MEM_MAX=2048m \
 MP_MEM_INIT=1024m \
 TZ=UTC \
 LC_ALL=en_US.UTF-8 \
 LANG=en_US.UTF-8 \
 LANGUAGE=en_US.UTF-8 \
 MP_DIR=${MP_DIR}

COPY container_files/usr-local-bin/* /usr/local/bin/

RUN if [ "${base_image}" = "ubuntu" ]; \
  then sed 's/main$/main universe/' -i /etc/apt/sources.list && \
       apt-get update -y && \
       apt-get install -y openjdk-${JAVA_VERSION}-jre-headless tzdata curl language-pack-en && \
       apt-get clean && \
       rm -rf /var/lib/apt/lists/*/tmp/* /var/tmp/* ; \
  else if [ "${base_image}" = "rockylinux" ]; \
  then dnf update -y && dnf install -y java-${JAVA_VERSION}-openjdk-headless tzdata bash which glibc-langpack-en && dnf clean all -y ; \
  else apk --update add --no-cache openjdk${JAVA_VERSION}-jre-headless curl libxml2-utils tzdata bash fontconfig ttf-dejavu musl musl-utils musl-locales ; \
  fi ; fi ; \
  mkdir -p "${MP_DIR}/bin/" ; \
  if [ ! -e "${MP_DIR}/bin/setenv.sh" ] ; then echo "#!/usr/bin/env bash" > "${MP_DIR}/bin/setenv.sh" ; fi ; \
  echo -n "export JAVA_HOME=" >> "${MP_DIR}/bin/setenv.sh" ; \
  find /usr/lib/jvm -maxdepth 1 -name "*openjdk*" -name "*${JAVA_VERSION}*" -type d | head -1 >> ${MP_DIR}/bin/setenv.sh ; \
  echo "[ \$(echo \${PATH} | grep -c openjdk) -eq 0 ] && PATH=\${PATH}:\${JAVA_HOME}/bin" >>${MP_DIR}/bin/setenv.sh

VOLUME ${MP_DIR}/var

HEALTHCHECK --interval=1m --timeout=30s --start-period=2m CMD /usr/local/bin/healthcheck.sh

EXPOSE 8080

CMD [ "/opt/midpoint/bin/midpoint.sh", "container" ]
