version: "3.3"

services:
  data_init:
    image: evolveum/midpoint:${MP_VER:-latest}
    command: [ "/opt/midpoint/bin/midpoint.sh", "init-native" ]
    environment:
     - MP_INIT_DB_CONCAT=/opt/db-init/init.sql
     - MP_INIT_CFG=/opt/mp-home
     - MP_INIT_LOOP=1
    volumes:
     - db_init:/opt/db-init
     - midpoint_home:/opt/mp-home

  midpoint_data:
    image: postgres:13-alpine
    depends_on:
     - data_init
    environment:
     - POSTGRES_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - POSTGRES_USER=midpoint
     - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
     - 5432:5432
    networks:
     - net
    secrets:
     - mp_database_password.txt
    volumes:
     - midpoint_data:/var/lib/postgresql/data
     - db_init:/docker-entrypoint-initdb.d/

  midpoint_server:
    image: evolveum/midpoint:${MP_VER:-latest}
    depends_on:
     - data_init
     - midpoint_data
    command: [ "/opt/midpoint/bin/midpoint.sh", "container" ]
    ports:
      - 8080:8080
    environment:
     - MP_SET_midpoint_repository_database=postgresql
     - MP_SET_midpoint_repository_jdbcUsername=midpoint
     - MP_SET_midpoint_repository_jdbcPassword_FILE=/run/secrets/mp_database_password.txt
     - MP_SET_midpoint_repository_jdbcUrl=jdbc:postgresql://midpoint_data:5432/midpoint
     - MP_SET_midpoint_keystore_keyStorePassword_FILE=/run/secrets/mp_keystore_password.txt
     - MP_UNSET_midpoint_repository_hibernateHbm2ddl=1
     - MP_NO_ENV_COMPAT=1
     - MP_ENTRY_POINT=/opt/midpoint-dirs-docker-entrypoint
    networks:
     - net
    secrets:
     - mp_database_password.txt
     - mp_keystore_password.txt
    volumes:
     - midpoint_home:/opt/midpoint/var
     - ./midpoint_server/container_files/mp-home:/opt/midpoint-dirs-docker-entrypoint/:ro

networks:
  net:    
    driver: bridge

secrets:
  mp_database_password.txt:
    file: ./configs-and-secrets/midpoint/database_password.txt
  mp_keystore_password.txt:
    file: ./configs-and-secrets/midpoint/keystore_password.txt
    
volumes:
  db_init:
  midpoint_data:
  midpoint_home:
