# Version for running Bats tests.
# Minimizes the number of ports mapped to localhost, to avoid collisions during testing.

version: "3.3"

services:
  midpoint_data:
    image: postgres:13-alpine
    environment:
     - POSTGRES_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - POSTGRES_USER=midpoint
     - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    expose:
     - 5432
    networks:
     - net
    secrets:
     - mp_database_password.txt
    volumes:
     - midpoint_data:/var/lib/postgresql/data

  midpoint_server:
    image: evolveum/midpoint:${image_tag:-latest}
    depends_on:
     - midpoint_data
    ports:
      - 8180:8080
    environment:
     - MP_SET_midpoint_repository_database=postgresql
     - MP_SET_midpoint_repository_jdbcUrl=jdbc:postgresql://midpoint_data:5432/midpoint
     - MP_SET_midpoint_repository_jdbcUsername=midpoint
     - MP_SET_midpoint_repository_jdbcPassword_FILE=/run/secrets/mp_database_password.txt
     - MP_SET_midpoint_repository_missingSchemaAction
     - MP_SET_midpoint_repository_upgradeableSchemaAction
     - MP_SET_midpoint_repository_schemaVersionIfMissing
     - MP_SET_midpoint_repository_schemaVariant
     - MP_SET_midpoint_keystore_keyStorePassword_FILE=/run/secrets/mp_keystore_password.txt
     - MP_ENTRY_POINT=/opt/midpoint-dirs-docker-entrypoint
     - MP_MEM_MAX
     - MP_MEM_INIT
     - JAVA_OPTS
     - TZ
    networks:
     - net
    secrets:
     - mp_database_password.txt
     - mp_keystore_password.txt
    volumes:
     - midpoint_home:/opt/midpoint/var
     - ./midpoint_server/container_files/mp-home/post-initial-objects:/opt/midpoint-dirs-docker-entrypoint/:ro

networks:
  net:    
    driver: bridge

secrets:
  mp_database_password.txt:
    file: ./configs-and-secrets/midpoint/database_password.txt
  mp_keystore_password.txt:
    file: ./configs-and-secrets/midpoint/keystore_password.txt
    
volumes:
  midpoint_data:
  midpoint_home:
