#!/bin/sh
set -x

apk add --no-cache curl

unset download

download=$(curl -sL https://github.com/google/go-containerregistry/releases | grep Linux_${1:-x86_64}.tar.gz | grep "<a href" | sed "s/[^\"]*\"\([^\"]*\)\".*/https:\/\/github.com\1/")

if [ "${download}" == "" ]
then
	download=$(curl -sL https://github.com/google/go-containerregistry/releases | grep Linux_${1:-i386}.tar.gz | grep "<a href" | sed "s/[^\"]*\"\([^\"]*\)\".*/https:\/\/github.com\1/")
fi

if [ "${download}" != "" ]
then
	curl -sL "${download}" | tar -xvzC /usr/local/bin crane
fi
