version: "3.4"

services:
  postgresql-midpoint:
    image: postgres:13-alpine
    container_name: book-postgresql-midpoint-chapter-7
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/mp_database_password.txt
      - POSTGRES_USER=midpoint
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
      - 15432:5432
    networks:
      - net
    secrets:
      - mp_database_password.txt
    volumes:
      - pg-midpoint_data:/var/lib/postgresql/data

  postgresql-crm:
    image: postgres:13-alpine
    container_name: book-postgresql-crm-chapter-7
    environment:
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_USER=crm
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - pg-crm_data:/var/lib/postgresql/data
      - ./book-chapter-common/container-book-postgres-crm_files:/docker-entrypoint-initdb.d/:ro

  ldap:
    image: osixia/openldap:stable
    container_name: book-ldap-chapter-7
    entrypoint: [ "/container/tool/run", "--copy-service" ]
    ports:
      - "10389:389"
    environment:
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_TLS=false
    networks:
      - net
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
      - ./book-chapter-common/container-book-ldap_files:/container/service/slapd/assets/config/bootstrap/ldif/custom/:ro

  midpoint:
    image: evolveum/midpoint:${MP_VERSION:-4.2}-alpine
    container_name: book-midpoint-chapter-7
    ports:
      - "8080:8080"
    environment:
      - MP_ENTRY_POINT=/opt/midpoint-dirs-docker-entrypoint
      - REPO_DATABASE_TYPE=postgresql
      - REPO_HOST=book-postgresql-midpoint-chapter-7
      - REPO_DATABASE=midpoint
      - REPO_USER=midpoint
      - REPO_PASSWORD_FILE=/run/secrets/mp_database_password.txt
      - MP_KEYSTORE_PASSWORD_FILE=/run/secrets/mp_keystore_password.txt
    networks:
      - net
    secrets:
      - mp_database_password.txt
      - mp_keystore_password.txt
    volumes:
      - midpoint_home:/opt/midpoint/var
      - ./book-chapter-7/container-book-midpoint_files:/opt/midpoint-dirs-docker-entrypoint/:ro
    depends_on:
      - ldap
      - postgresql-crm
      - postgresql-midpoint

networks:
  net:    
    driver: bridge

secrets:
  mp_database_password.txt:
    file: ./book-chapter-common/configs-and-secrets/database_password.txt
  mp_keystore_password.txt:
    file: ./book-chapter-common/configs-and-secrets/keystore_password.txt

volumes:
  midpoint_home:
    name: book-midpoint_home-chapter-7
  ldap_conf:
    name: book-ldap_conf-chapter-7
  ldap_data:
    name: book-ldap_data-chapter-7
  pg-midpoint_data:
    name: book-postgresql-midpoint_data-chapter-7
  pg-crm_data:
    name: book-postgresql-crm_data-chapter-7
