version: "3.4"

services:
  postgresql-midpoint:
    image: postgres:13-alpine
    container_name: book-postgresql-midpoint-chapter-2
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/mp_database_password.txt
      - POSTGRES_USER=midpoint
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
      - 5432:5432
    networks:
      - net
    secrets:
      - mp_database_password.txt
    volumes:
      - pg-midpoint_data:/var/lib/postgresql/data

  postgresql-crm:
    image: postgres:13-alpine
    container_name: book-postgresql-crm-chapter-2
    environment:
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_USER=crm
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
      - 15432:5432
    networks:
      - net
    volumes:
      - pg-crm_data:/var/lib/postgresql/data
      - ./book-chapter-common/container-book-postgres-crm_files:/docker-entrypoint-initdb.d/:ro

  ad:
    image: sonohara/samba4-ad-dc
    container_name: book-ldap-chapter-2
    privileged: true
    networks:
      - net
    ports:
    - "389:389"
    environment:
    - DOCKER_DEBUG=1
    - DNS_FORWARD=8.8.8.8
    - DNS_DOMAIN=sambaad.local
    - AD_PASSWORD=PASS0rd123
    - AD_REALM=sambaad.local
    - AD_DOMAIN=SAMBAAD

  midpoint:
    image: evolveum/midpoint:${MP_VERSION:-4.4}-alpine
    # image: sakazuki/midpoint:arm64
    container_name: book-midpoint-chapter-2
    ports:
      - "8080:8080"
    environment:
      - MP_ENTRY_POINT=/opt/midpoint-dirs-docker-entrypoint
      - REPO_DATABASE_TYPE=postgresql
      - REPO_HOST=book-postgresql-midpoint-chapter-2
      - REPO_DATABASE=midpoint
      - REPO_USER=midpoint
      - REPO_PASSWORD_FILE=/run/secrets/mp_database_password.txt
      - MP_KEYSTORE_PASSWORD_FILE=/run/secrets/mp_keystore_password.txt
    networks:
      - net
    secrets:
      - mp_database_password.txt
      - mp_keystore_password.txt
    volumes:
      - midpoint_home:/opt/midpoint/var
      - ./book-chapter-2/container-book-midpoint_files:/opt/midpoint-dirs-docker-entrypoint/:ro
    depends_on:
      - postgresql-crm
      - postgresql-midpoint

networks:
  net:    
    driver: bridge

secrets:
  mp_database_password.txt:
    file: ./book-chapter-common/configs-and-secrets/database_password.txt
  mp_keystore_password.txt:
    file: ./book-chapter-common/configs-and-secrets/keystore_password.txt

volumes:
  midpoint_home:
    name: book-midpoint_home-chapter-2
  ldap_conf:
    name: book-ldap_conf-chapter-2
  ldap_data:
    name: book-ldap_data-chapter-2
  pg-midpoint_data:
    name: book-postgresql-midpoint_data-chapter-2
  pg-crm_data:
    name: book-postgresql-crm_data-chapter-2
